export default {
  Primary: '#15EB83',
  Secondary: '#0ABA65',
  Accent: '#EB15B6',
  AppBackground: 'linear-gradient(180deg, #ffffff 0%, #ffffff 100%)',
  AppBackgroundColor: '#FFFFFF',
  AppText: '#15EB83',
  AppTextSecondary: '#0ABA65',
  AppBorder: '#EEF2F0',
  AppBorderSecondary: '#EEF2F0',
  BixOutlineStageOne: '#0ABA65',
  BixOutlineStageTwo: '#FFFFFF',
  BixOutlineStageThree: '#FFFFFF',
  BixFillStageOne: '#15EB83',
  BixFillStageTwo: '#15EB83',
  BixFillStageThree: '#15EB83',
  CardBackground: '#FFFFFF',
  CardBackgroundColor: '#FFFFFF',
  CardBackgroundSecondary: 'rgba(0, 0, 0, 0.05)',
  CardText: '#191919',
  CardTextSecondary: '#979797',
  CardBorder: '#EEF2F0',
  CardBorderSecondary: '#EEF2F0',
  NavLogo: '#15EB83',
  NavBackgroundStageOne: '#FFFFFF',
  NavBackgroundStageTwo: '#FFFFFF',
  NavBackgroundStageThree: '#FFFFFF',
  NavColor: '#0ABA65',
  NavActive: '#0ABA65',
  NavIconStageTwo: '#0ABA65',
  NavInactive: '#979797',
  NotificationColor: '#15EB83',
  NotificationText: '#757575',
  ErrorColor: '#FF0000',
  ErrorText: '#FFFFFF',
  SuccessColor: '#00FF00',
  SuccessText: '#FFFFFF',
  Paper: '#FCFCFC',
  PricePositive: '#0ABA65',
  PriceNegative: '#FF0000',
  VeryFaintPrimary: '#F9FFFC',
  desktop: {
    // Values for the above colors that are to be set ONLY on desktop
    // What if we need a value on desktop, but not on mobile?
    AppBackground: '#FFFFFF',
    AppBackgroundColor: '#FFFFFF',
    AppText: '#191919',
    AppTextSecondary: '#979797'
  },
  tablet: {
    // Values for the above colors that are to be set ONLY on desktop
  },
  mobile: {
    // Values for the above colors that are to be set ONLY on desktop
  },
  NameColors: {
    A: '#53B805',
    B: '#FA4F05',
    C: '#D33C3C',
    D: '#9D73DF',
    E: '#39E4FB',
    F: '#69A1ED',
    G: '#FA8905',
    H: '#31EC7B',
    I: '#FF6A6A',
    J: '#FB39D6',
    K: '#CD7EFE',
    L: '#41A66F',
    M: '#6459E5',
    N: '#41A66F',
    O: '#CD7EFE',
    P: '#FB39D6',
    Q: '#FF6A6A',
    R: '#31EC7B',
    S: '#FA8905',
    T: '#69A1ED',
    U: '#39E4FB',
    V: '#9D73DF',
    W: '#D33C3C',
    X: '#FA4F05',
    Y: '#53B805',
    Z: '#6459E5'
  }
}
